version: '3.1'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: sriram-php
    depends_on:
      - db
    ports:
      - "5001:80"

  db:
    container_name: db
    image: "mysql:8.0.2"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Adminpass19'
    ports:
      - "6033:3306"

